### ISSUE TITLE
Versioning the models

### ISSUE THREAD

**Issue by geohacker** [hotosm/ml-enabler#17]
We've been discussing whether we should enforce a versioning mechanism for models or allow arbitrary.

First some background on why this is important:
* Models will have several versions - different iterations would have improvements and new features
* Predictions will be spread across different versions - for example the predictions for US could be from v1 and predictions for Kenya could be from v2. 
* By default ml-enabler should always give the most recent predictions. That means predictions from the most recent version.
* Currently, we are storing model version as part of the prediction along with a timestamp. But this has a few problems. 

What's up with versions?
* Even though semver is widely used, some models still tend use string combinations in as a version string when pushing to docker. Sometimes it's `latest`
* If we allow string versions, we would have to rely on a timestamp to fetch the latest predictions for a bbox.
* The timestamp is unreliable because the v2 could have been predicted before v1. 

The best approach @batpad and I can think of is this:
* Enforce semver for model versions
* Create a new table called model_version
* Every time a new prediction is submitted, it should mention the version of the model
* If this version isn't registered in the model_versions table, we'll add it
* When a client requests for predictions, we'll pick the latest version of prediction for the bbox using the semver version and not rely on timestamp.

@wronk does this sound reasonable to you?
@xamanu do you have any thoughts?

**Comment by wronk** [comment]
@geohacker, that sounds good to me

Do you think we should also store the hash of the model image or no?

**Comment by geohacker** [comment]
Awesome. I think we've a clear path forward!
@wronk I think we will store the hash, just to be safe and perhaps future proof.
