### ISSUE TITLE
Define database schema

### ISSUE THREAD

**Issue by geohacker** [hotosm/ml-enabler#2]
We want to store the following info:

1. Model information - name, source, last_updated_timestamp
2. Tile level prediction - z19 or z21 or whatever the model returns. Ideally stored as jsonb `{x/y/z: {'ml_key': value, 'ml_key_2': value, 'geometry_url': 'url'}}`
3. Store geometry URL - the model may produce vectors that are stored somewhere (perhaps on s3). This is part of json.
4. Aggregations - for a particular bbox / TM project, aggregations can be stored so we don't have to recalculate all the time

@wronk anything else we should include? 

cc @hotosm/development-seed

**Comment by wronk** [comment]
For model information, let's add the DockerHub file and DockerHub hash value

**Comment by geohacker** [comment]
Per chat with @batpad, I think we'll add the following columns to predictions table:
* version. A model version when this prediction was generated. This can be used in case a model submits predictions for same or different bboxes or over several iterations of its own code.
* predicted bbox. When the model is posting prediction to the ml-enabler, it should post the bbox over which these predictions are.
