### ISSUE TITLE
Write post-processing function for Looking Glass predictions

### ISSUE THREAD

**Issue by wronk** [hotosm/ml-enabler#20]
After we get a building segmentation mask from Looking Glass, we need to convert this array into a single float value representing predicted building area.

**Post-processing flow**
1. Read in looking-glass predictions
2. Threshold (non-negative pixels are predicted to be part of a building) to create a binary mask
3. Sum up num positive pixels in binary mask
4. Multiply by sq meters per pixel
5. Return total predicted building area as a float

@geohacker and @xamanu, step 4 can get tricky depending on how precise we want to be. Zoom 18 pixels are nominally 0.596m on a side, but this varies a little depending on distance from the equator. Do we want to try to calculate area/pixel internally, or leave this as a parameter for the user to pass?

**Comment by geohacker** [comment]
> Zoom 18 pixels are nominally 0.596m on a side,

Talking to a few folks on our team and thinking a lot about #23, we should aggregate looking-glass prediction at z16 to avoid the overhead of aggregating them from z18 in the database. z16 is roughly a about 2m sq, and on the map would be a small road or part of a street. z18 is far too granular for the client-side use-cases. This for instance will be more accurate for aggregating tasking manager task squares. 

cc @batpad

**Comment by wronk** [comment]
I added the a simple post processing function in [utils_postproc.py](https://github.com/developmentseed/looking-glass-pub/blob/master/looking_glass/utils_postproc.py) and also updated the ipython notebook example to use it

@geohacker, okay if I close this and we continue discussion around z18 vs z16 in #23? I can also open a separate issue about figuring out pixel sizes

**Comment by geohacker** [comment]
@wronk thank you! sounds good.
