### ISSUE TITLE
Calculate area per pixel in z18 tiles

### ISSUE THREAD

**Issue by wronk** [hotosm/ml-enabler#24]
Splitting this issue off #20, we need to figure out the spatial area of each satellite image pixel. This allows us to estimate total building area within an image. In z18 images, pixels are nominally 0.596m on a side, but that varies depending on the tile's latitude.

@geohacker and @xamanu, I'll run this by the DS folks, but do you know any other geospatial experts we should ask?

**Comment by geohacker** [comment]
@wronk Sean, Vincent or Drew likely be able to help I think. I want to point out that for practical purposes, we want to get looking-glass predictions are z16. We still have to figure out the answer to the question above, but I'd strongly recommend z16 to avoid lots of overhead.

**Comment by wronk** [comment]
@geohacker, sounds good. I agree with your assessment in #23 

We can send batches of z18 images to the model for inference, and then immediately calculate building area, and aggregate down to z16 for storage.

**Comment by wronk** [comment]
Per Sean from DS, we should be able to use this:
https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Resolution_and_Scale

We can probably just calculate the average latitude for a task (since it shouldn't vary much across its tile squares), calculate m/pixel, and then use that in our post-processing scripts

**Comment by wronk** [comment]
Added this for calculating pixel area:

https://github.com/developmentseed/looking-glass-pub/blob/master/looking_glass/utils_postproc.py#L42

cc @geohacker @batpad

**Comment by geohacker** [comment]
This is done!
