### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by geohacker** [hotosm/ml-enabler#3]
Sketching out an API, we can change this along the way:

## model to ml-enabler
* [x] POST /ml-enabler/register/<model_name> - may not implement now, but should have this endpoint to register models
* [x] POST /ml-enabler/<model_name>/ with a payload of JSON tile data

## ml-enabler to TM
* [x] GET /ml-enabler/models/ - fetch all available models
* [x] GET /ml-enabler/<model_name>/predictions/bbox - get aggregated prediction for the bbox
* [x] POST /ml-enabler/<model_name>/predictions/project - with the TM project geojson as the payload will return aggregated prediction per task

cc @wronk @batpad @xamanu

**Comment by pantierra** [comment]
Thanks, @geohacker. Makes a lot of sense, for the first API definition. What do you think @fitoria and @JorgeMartinezG?

**Comment by geohacker** [comment]
All the above endpoints are done -  https://github.com/hotosm/ml-enabler/blob/master/ml_enabler/__init__.py#L38-L44
