### ISSUE TITLE
Docker publish fails

### ISSUE THREAD

**Issue by geohacker** [hotosm/ml-enabler#42]
@dakotabenjamin looks like the ci task `publish-latest` is failing with `Must provide --username with --password-stdin` on Circle https://circleci.com/gh/hotosm/ml-enabler/11?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Not entirely sure, but perhaps the dockerhub username or password is missing in circle? Thanks!

**Comment by dakotabenjamin** [comment]
You're correct. @xamanu I used my personal credentials temporarily. I was reading about "service users" for docker hub but I'm not sure if that's how to properly set credentials for a build like this. What do you think?
