### ISSUE TITLE
ci + deployment

### ISSUE THREAD

**Issue by geohacker** [hotosm/ml-enabler#6]
@xamanu opening this ticket to make sure we setup deploying this project from the get go.  Who will be able to help us from HOT to do this? 

Should we use AWS ECS via Fargate? Or do you have a convention at HOT?

**Comment by dakotabenjamin** [comment]
I can be the point person for this. Fargate sounds like a good choice for this platform. Please let me know what you need from me for getting this set up, and you can usually reach me on slack as well.

**Comment by geohacker** [comment]
@dakotabenjamin thank you! 

This project now has a Dockerfile that spins up gunicorn to run the service. It's now ready to be put behind ECS. It'll need an RDS resource to connect to the database. I'm now moving on to building all the app logic so I leave it up to you and @xamanu for cloudformation setup etc.

**Comment by dakotabenjamin** [comment]
For the environment variables on a production stack, is the MLENABLER_TEST_DB a required thing to have?

**Comment by geohacker** [comment]
@dakotabenjamin no it's not required - we can create a production.env if that's a cleaner approach, and add the testdb env in circle. cc @batpad

**Comment by geohacker** [comment]
@xamanu @dakotabenjamin - could we get this deployed soon? We're pretty much wrapping up development on the API and would really like to demo the pipeline and get feedback.
